@ECHO OFF
CLS

SET RELEASE_DIR=Game
SET GAME_EXE_COMPILED=Game Engine.exe
SET GAME_EXE_DEBUG=Debug.exe
SET GAME_DEBUG_DIR=Game Engine\Debug

IF NOT EXIST "%RELEASE_DIR%" MKDIR "%RELEASE_DIR%"

ECHO Copying Debug executable...
XCOPY "%GAME_DEBUG_DIR%\%GAME_EXE_COMPILED%" "%RELEASE_DIR%" /I /Y
IF EXIST "%RELEASE_DIR%\%GAME_EXE_DEBUG%" DEL "%RELEASE_DIR%\%GAME_EXE_DEBUG%"
REN "%RELEASE_DIR%\%GAME_EXE_COMPILED%" "%GAME_EXE_DEBUG%"

ECHO.
ECHO Done!

ECHO.
ECHO Running Debug executable...
CD "%RELEASE_DIR%"
"%GAME_EXE_DEBUG%"

ECHO.
ECHO Removing Debug executable...
IF EXIST "%RELEASE_DIR%\%GAME_EXE_DEBUG%" DEL "%RELEASE_DIR%\%GAME_EXE_DEBUG%"

ECHO.
PAUSE
